## Numpy

Numpy es una librería para el control y manejo de arreglos enfocado en operaciones matemáticas , muy utilizado en el machine learning , matemáticas y la ciencia de datos. Lo usaremos demasiado a lo largo del grupo y será fundamental para la creación de muchas cosas

Es necesario saber que un vector no es un más que una lista, pero enfocada más en las operaciones matemáticas , es un conjunto de n elementos , estos puedes pueden ser de múltiples dimensiones, cuando son unidimensional son vector , bidimensional son matrices y varias dimensiones se llaman tensores.

Ejemplo

$A =[5,4,3,2]$ Es un vector de 4 elementos

$B =[[5,4,3,2],[8,5,1,6]]$ Es una matriz de 2 dimensiones y 8 elementos

Recordar que Matemáticamente los elementos empiezan desde la posición 1, pero en programación se trabaja desde el 0

## Instalar numpy

Para instalar numpy podemos usar el siguiente comando en nuestra terminal

`pip install numpy` , conociendo que debemos de tener ya pip en ella

Por comodidad utilizaremos Google collab pues ya lo tiene integrado y es mas facil

In [1]:
import numpy as np

a=np.array([5,4,3,2])

b=np.array([[5,4,3,2],[8,5,1,6]])

print(a)


[5 4 3 2]


## Crear arreglos

Podemos crear un arreglo usando la funcion np.array dependiendo si solo ponemos unos corchetes se creara un vector , cuando se ponen otros se creara una matriz

In [2]:
print(b)

[[5 4 3 2]
 [8 5 1 6]]


In [3]:
print(b.shape) #Podemos ver sus dimensiones usando el atributo .shape , filas y columnas

print(b.size) #Podemos ver la cantidad de elementos usando .size

(2, 4)
8


In [4]:
c=np.arange(1,10)

c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos crear un arreglo de valores lineales usando arange que tiene 3 parametros ,Inicio,final y cantidad de pasos

In [5]:
c2=np.arange(1,12,2)

c2

array([ 1,  3,  5,  7,  9, 11])

In [6]:
d=np.linspace(1,3,50)

d

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

Podemos usar np.linspace para crear un arreglo de un espacio infinitidecimal entre un numero y otro , inicio, final y cantidad de elementos a tomar. Es muy utilizada para la graficacion de modelos 

In [7]:
zero = np.zeros((3,3)) #Crear un arreglo o matriz con ceros

zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#Podemos usar bucles for para recorrer arreglos de numpy, forma para matrices
print(b)

for row in b:
    for column in row:
        print(column)

[[5 4 3 2]
 [8 5 1 6]]
5
4
3
2
8
5
1
6


In [9]:
#Otra forma mas facil, solo para vectores

for i in a:
    print(i)

5
4
3
2


## Redimensionar

**Podremos redimensionar arreglos a nuestro favor o en automatico, esto es muy importante para algunos modelos de ML**

In [10]:
print('Antes')

print(b)

print(b.shape) #Como vemos que tiene 2 filas y cuatro columnas , podemos hacerlo convertirlo en una forma matematica real

print('Despues')

print(b.reshape(4,2))

Antes
[[5 4 3 2]
 [8 5 1 6]]
(2, 4)
Despues
[[5 4]
 [3 2]
 [8 5]
 [1 6]]


In [11]:
print(b.reshape(-1,4)) #El -1 lo transforma a una forma aleatoria posible ya sea la fila o columna

[[5 4 3 2]
 [8 5 1 6]]


## Indexeo y slicing

Estas funciones son muy importantes y fundamentales para los arreglos, aunque son un poco dificiles de aprender

In [12]:
print(a)

#Podemos acceder al primer elemento usando donde [] es la fila
print(a[0])

#Podemos acceder al ultimo elemento usando
print(a[-1])

#Podemos acceder al penultimo elemento usando
print(a[-2])

#Podemos acceder a cualquier elemento existente usando esta estructura n-1, este es el segundo elemento
print(a[1])

[5 4 3 2]
5
2
3
4


In [13]:
#Lo mismo ocurre con las matrices solo que ya son 2 dimensiones, primer elemento

print(b[0][0])

#Ultimo elemento
print(b[-1][-1])

#Un elemento random ,usando la estructura de fila y columna [][]

print(b[1][2])

5
6
1


En NumPy, puedes usar varias formas de indexación para seleccionar elementos específicos de un array. Aquí te dejo algunos ejemplos:

`SIEMPRE VA PRIMERO EL : EN CUALQUIER CASO QUE SE USE`

1. **Indexación básica**: Puedes seleccionar un elemento específico de un array proporcionando su índice. Por ejemplo, `a[0]` selecciona el primer elemento de `a`.

2. **Rebanado**: Puedes seleccionar un rango de elementos utilizando la notación de rebanado. Por ejemplo, `a[1:3]` selecciona los elementos desde el índice 1 hasta el índice 3 (exclusivo).

3. **Indexación booleana**: Puedes seleccionar elementos que cumplan una condición específica. Por ejemplo, `a[a > 2]` selecciona todos los elementos de `a` que son mayores que 2.

4. **Indexación de matrices enteras**: Puedes seleccionar elementos en un orden específico o más de una vez. Por ejemplo, `a[[2, 1, 0]]` selecciona los elementos en el orden inverso.

5. **Indexación multidimensional**: Puedes seleccionar elementos de arrays multidimensionales. Por ejemplo, `a[1, 2]` selecciona el elemento en la segunda fila y la tercera columna de `a`.

6. **Indexación con pasos**: Puedes seleccionar elementos con un paso específico. Por ejemplo, `a[::2]` selecciona cada segundo elemento de `a`.

7. **Seleccionar una fila específica**: Si tienes un array bidimensional, puedes seleccionar una fila específica utilizando su índice. Por ejemplo, `a[2,:]` selecciona todos los elementos de la tercera fila.

8. **Seleccionar una columna específica**: De manera similar, puedes seleccionar una columna específica utilizando su índice. Por ejemplo, `a[:,1]` selecciona todos los elementos de la segunda columna.
    
9. **Seleccionar elementos específicos**: Puedes seleccionar elementos específicos de un array proporcionando una lista de índices. Por ejemplo, `a[[0, 2]]` selecciona los elementos en los índices 0 y 2.

10. **Seleccionar todos los elementos sin tomar un elemento**:  `a[1:]`  Este comando selecciona todos los elementos desde el segundo elemento hasta el final
    
- data[-1:]: Este comando selecciona todos los elementos de data desde el último elemento hasta el final. En Python, un índice negativo se utiliza para contar desde el final de la lista, por lo que -1: selecciona solo el último elemento.    

11. **Todas menos la ultima fila  data`[:-1,:]` (bidimensional)**: Este comando se utiliza cuando data es un array bidimensional (como una matriz o un DataFrame en pandas). :-1 significa que se toman todas las filas desde la primera hasta la penúltima (excluyendo la última fila). El : después de la coma indica que se toman todas las columnas. Por lo tanto, este comando selecciona todas las columnas y todas las filas excepto la última.

12. **Todas las columnas menos la ultima(Bidimensional)**: `data[:, :-1]` En este caso, el : antes de la coma indica que se toman todas las filas. El :-1 después de la coma significa que se toman todas las columnas desde la primera hasta la penúltima (excluyendo la última columna). Por lo tanto, este comando selecciona todas las filas y todas las columnas excepto la última.

**Algunos ejemplos**

In [14]:
print(b[b>2])

print('///')

matriz=np.arange(1,10).reshape(3,3,)

print(matriz)

print('///')

print(matriz[1,:]) #Toma la segunda fila y todas las columnas :

print('///')
print(matriz[::,1]) #Toma todas las filas y solo el segundo elemento de estas 

print('///')

print(matriz[-1,:])# De las filas toma la ultima y de las columnas todas

[5 4 3 8 5 6]
///
[[1 2 3]
 [4 5 6]
 [7 8 9]]
///
[4 5 6]
///
[2 5 8]
///
[7 8 9]


In [16]:
a

array([5, 4, 3, 2])

In [24]:
print(np.append(a,256)) #Podemos agregar elementos a un arreglo

print(np.append(a,[[5],[7]]))


[  5   4   3   2 256]
[5 4 3 2 5 7]


En numpy existen axis que son los ejes de referencia en donde 1 es una columna y 0 es una fila , con esto podemos hacer que

In [26]:
# Crear un arreglo bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2d)

# Agregar una columna al final del arreglo
new_array_2d_col = np.append(array_2d, [[7], [8]], axis=1)

print(new_array_2d_col)

[[1 2 3]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]]


In [29]:
print(a)

print(np.delete(a,-1)) #Puedo eliminar usando delete seguido de la posicion del elemento a eliminar

[5 4 3 2]
[5 4 3]
