# Operaciones entre arreglos , matematicas y estadistica.

Numpy nos permite realizar una serie de operaciones usando los arreglos en donde estas seran fundamentales para el tema de implementacion de modelos o de algunos datos fundamentales, empezare a mostrar las basicas y algunas mas especificas

In [2]:
import numpy as np

array_1=np.array([5,4,3,2]) #Creamos 2 arreglos de igual dimension

array_2=np.array([10,4,5,1])

#Podemos sumarlos entre si , la clasica suma punto a punto de vectores o matrices

print(np.add(array_1,array_2),'Usando la funcion')

# O simplemente usar el operador +

print(array_1+array_2,'Usando el operador')

print(np.subtract(array_2,array_1)) #Lo mismo para dividir

print(np.multiply(array_2,array_1)) #Lo mismo para multiplicar entre escalares, no es multiplicacion de vectores y matrices


[15  8  8  3] Usando la funcion
[15  8  8  3] Usando el operador
[ 5  0  2 -1]
[50 16 15  2]


Recordar que la multiplicacion entre matrices y el producto a escalar de estas es diferentes, pues en uno se multiplica elemento a elemento y en la otra usa una tecnica diferente. **La de arriba se llama producto punto a punto**

Arriba vimos la que solo multiplica sus componentes punto a punto , vamos a ver la multiplicacion de matrices normal y la de un escalar por una matriz

## Matriz por escalar

In [3]:
matriz_ones=np.ones((3,3),int)

print(matriz_ones)

#Si multiplicamos un escalar por un matriz obtenemos

print(5*matriz_ones) #Aqui si es normal pues el numero por cada uno de los elementos

#Sin embargo ahora hagamos la multiplicacion de matrices


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
matriz_2x2_A=np.random.randint(0,10 ,size=((2,2))) #Me sirve para generar una matriz random con valores

print(matriz_2x2_A)

matriz_2x2_B=np.random.randint(0,10 ,size=((2,2)))

print(matriz_2x2_B)

print(np.dot(matriz_2x2_A,matriz_2x2_B)) 


[[0 1]
 [5 0]]
[[3 0]
 [0 4]]
[[ 0  4]
 [15  0]]


Notese que si multiplicamos elemento a elemento no se tiene lo que concuerda ya que aqui se multiplica la fila de uno por la columna de otro, se que es algo raro pero asi funciona. **Las matrices de igual tamaño siempre se pueden multiplicar , si tienen diferente tamaño se debe de realizar un analisis para comprobar si son posibles**

In [5]:
#Por ultimo algunas funciones basicas mas son

print(np.power(array_1,5)) #Elevar matrices a un numero en especifico

print(np.power(matriz_ones,5))

print(np.power(matriz_2x2_A,5))



[3125 1024  243   32]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[   0    1]
 [3125    0]]


## Algunas aplicaciones a la estadistica

In [6]:
array_example=np.arange(1,11)

print(array_example)

print(np.mean(array_example)) #Podemos hallar la media 

print(np.median(array_example)) #Podemos hallar la mediana , em este caso por el tipo de arreglo nos dio igual

print(np.std(array_example)) #Podemos hallar la desviacion estandar de un arreglo

print(np.var(array_example)) #Podemos hallar la varianza


[ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5
2.8722813232690143
8.25


Existen muchas mas pero con estas puedes avanzar bastante y ver mas alla para ampliar tu conocimiento

## Algunas aplicaciones del algebra lineal con numpy

Mostrare algunas operaciones del algebra lineal que pueden hacer con numpy , quizas en el momento no las veas utiles pero las puedes aplicar en el dia a dia o para obtener un valor en especifico mas adelante cuando creemos los modelos

In [8]:
matriz_2x2_B

array([[3, 0],
       [0, 4]], dtype=int32)

In [13]:
print(np.linalg.det(matriz_2x2_B)) #Podemos hallar el determinante de una matriz

print(np.linalg.inv(matriz_2x2_B)) #Podemos hallar la inversa de una matriz

print(np.linalg.matrix_rank(matriz_2x2_B)) #Podemos hallar el rango de una matriz

#Hallar la transpuesta de una matriz
print(matriz_2x2_B.T)

#Hallar la traza de una matriz
print(np.trace(matriz_2x2_B))





12.0
[[0.33333333 0.        ]
 [0.         0.25      ]]
2
[[3 0]
 [0 4]]
7


Podemos resolver sistemas de ecuaciones lineales de n dimensiones usando numpy.

Usando la formula de 

$$AX=B$$

-Donde A son los coeficientes de los S.E.L 

-X son las incognitas

-B son los valores independientes igualados

In [29]:
A=np.array([[2,1,-2],[3,0,1],[1,1,-1]])

B=np.array([[-3],[5],[-2]])

print(A)

print("------")

print(B)

#Resolvemos el sistema
print("--------")

operation=np.linalg.solve(A,B)

print('Las respuestas para x , y ,z son \n',operation)

#Comprobamos si esta bueno
print(np.allclose(np.dot(A,operation),B)) #Primer parametro la matriz A , el resultado y por ultimo B la matriz
#Retorna un boolean

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
------
[[-3]
 [ 5]
 [-2]]
--------
Las respuestas para x , y ,z son 
 [[ 1.]
 [-1.]
 [ 2.]]
True
